name = "serverless-chat"
main = "src/index.ts"
compatibility_date = "2022-12-16"

[durable_objects]
bindings = [
    {name = 'CHAT', class_name = 'ChatRoom'}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"] # Array of new classes
